---
title: Promise的使用
date: 2019-10-01
tags:
 - JavaScript
categories:
 -  JavaScript
---

> Promise是异步编程的一种解决方案，在ES6中Promise被列为了正式规范，统一了用法，原生提供了Promise对象。

## 基本用法

```js
  let promise = new Promise((reslove, reject) => {
    setTimeout(() => {
      if (Math.random() * 50 >= 25) {
        reslove('成功') // 成功后的回调
      } else {
        reject('失败') // 失败后的回调
      }
    }, 1000)
  })
  promise.then((data) => {
    console.log('success', data)
  }, (err) => {
    console.log('error', err)

  })
```

## 链式写法

```js
  // .then()返回一个新的Promise实例，因此它可以被链式调用
  new Promise((reslove, reject) => {
    setTimeout(() => {
      if (Math.random() * 50 >= 25) {
        reslove('成功') // 成功后的回调
      } else {
        reject('失败') // 失败后的回调
      }
    }, 1000)
  }).then(data => {
    console.log("success", data)
  }).catch(err => {
    console.log("error", err)
  })
```

## 使用throw抛出异常

```JS
  new Promise((reslove, reject) => {
    setTimeout(() => {
      if (Math.random() * 50 >= 25) {
        reslove('成功') // 成功后的回调
      } else {
        throw new Error('失败') // 抛出异常
      }
    }, 1000)
  }).then(data => {
    console.log("success", data)
  }).catch(err => {
    console.log("error", err) // 失败时catch没有被触发而是直接抛出异常
  })
```

## 使用Promise.all()批量执行实例

```js
  let promise1 = new Promise((reslove, reject) => {
    setTimeout(() => {
      if (Math.random() * 50 >= 5) {
        reslove('成功') // 成功后的回调
      } else {
        reject('失败') // 失败后的回调
      }
    }, 1000)
  })
  let promise2 = new Promise((reslove, reject) => {
    setTimeout(() => {
      if (Math.random() * 50 >= 5) {
        reslove('成功') // 成功后的回调
      } else {
        reject('失败') // 失败后的回调
      }
    }, 1000)
  })
  let promise3 = new Promise((reslove, reject) => {
    setTimeout(() => {
      if (Math.random() * 50 >= 5) {
        reslove('成功') // 成功后的回调
      } else {
        reject('失败') // 失败后的回调
      }
    }, 1000)
  })
  Promise.all([promise1, promise2, promise3]) // 当数组中所有promise实例执行完毕后再返回新的promise实例
    .then(data => { // 当数组中的所有promise实例都返回reslove状态才会触发.then(),返回的结果用数组表示
      console.log("success", data) 
    }).catch(err => { // 当数组中有一个promise实例返回reject状态就会触发.catch()
      console.log("error", err) 
    })
```

## 使用Promise.race()竞速模式

```js
  let promise1 = new Promise((reslove, reject) => {
    setTimeout(() => {
      if (Math.random() * 50 >= 5) {
        reslove('成功') // 成功后的回调
      } else {
        reject('失败') // 失败后的回调
      }
    }, 1000)
  })
  let promise2 = new Promise((reslove, reject) => {
    setTimeout(() => {
      if (Math.random() * 50 >= 5) {
        reslove('成功') // 成功后的回调
      } else {
        reject('失败') // 失败后的回调
      }
    }, 1000)
  })
  let promise3 = new Promise((reslove, reject) => {
    setTimeout(() => {
      if (Math.random() * 50 >= 5) {
        reslove('成功') // 成功后的回调
      } else {
        reject('失败') // 失败后的回调
      }
    }, 1000)
  })
  Promise.race([promise1, promise2, promise3]) // 当数组中有一个promise实例执行完毕后就返回新的promise实例
    .then(data => { // 当数组中有一个promise实例返回reslove状态就会触发.then()
      console.log("success", data) 
    }).catch(err => { // 当数组中有一个promise实例返回reject状态就会触发.catch()
      console.log("error", err) 
    })
```